### ISSUE TITLE
Code cleanup and compatibility workout

### ISSUE THREAD

**Issue by DoZ10** [GoSecure/DLLPasswordFilterImplant#5]
Get rid of the ```double``` type and use _GlobalAlloc_, _GlobalFree_ instead of _malloc_ & _free_. Also try to use Windows types instead of standard C. Things like that.

Also, we must make sure it compiles and works on x86 and x64 from Windows 7 to latest.

**Comment by alxbl** [comment]
Pending tests on a Windows Server 2008 32 bit OS. 

If it all works I'll resolve this and add x86 support to the Empire module.

**Comment by alxbl** [comment]
Looks like the only version of Windows Server to support 32 bit is Windows Server 2008 SP1. I've managed to make the DLL work in a proof of concept on a 32 bit OS, but LSA seems to refuse to load it. I don't want to waste too much time on supporting a single OS unless it turns out that there's a real need to attack 32bit DCs during engagements.

If that turns out to be he case we can open another issue for x86 support and implement it properly then. For now I'll focus on #9 and close this issue.
