### ISSUE TITLE
Pull request submitted to integrate project in the Empire project

### ISSUE THREAD

**Issue by Le-non** [GoSecure/DLLPasswordFilterImplant#9]
ref: https://github.com/EmpireProject/Empire/pull/1095

**Comment by alxbl** [comment]
Will follow-up on this. Code is almost done, just needs additional testing

**Comment by alxbl** [comment]
Empire is no longer maintained. There are forks, but given the opsec implications, I think we can drop this unless/until people show interest in having support in Empire.

Closing.

**Comment by jessefmoore** [comment]
It’s been revised here: https://github.com/BC-SECURITY/Empire

**Comment by alxbl** [comment]
@jessefmoore If you think the implant would be a valuable addition to the project, I don't mind re-opening the PR there, but I'm a bit swamped so it might take me some time to get around to testing on the BC-SECURITY branch. That being said, I'd be happy to if even one person thinks it would be helpful.

Cheers,
Alex

**Comment by jessefmoore** [comment]
Hi Alex! My only concern is that it doesn’t duplicate this: https://github.com/BC-SECURITY/Empire/blob/master/data/module_source/persistence/Install-SSP.ps1 Otherwise, yes value add 😀

**Comment by alxbl** [comment]
That module looks like it already does most of what is required! The only thing we do differently (extra) is add extra registry keys for exfiltration domain and public key configuration.

This renders the Empire module we wanted to contribute redundant. In that case I would rather embed the public key and exfiltration domain into the binary so that it can be dropped through `Install-SSP` and document this in our repository. This is actually a lot less work on our part as well even though it will require users to compile their own version of DLLPasswordFilterImplant.

I don't know how I wasn't aware of this persistence module, and I'm surprised it's been around since 2015 :)

Thanks for the heads up! I'll modify the code base and documentation to mention `Install-SSP` instead.
